### ISSUE TITLE
Weird error message during edo checkout, when there's already a stage checked out and fetched

### ISSUE THREAD

**Issue by YuanboXue-Amber** [dankox/endevor-cli#3]
I have an empty folder, I did my `edo init`, 
and then:
`edo checkout DEV-1-ESCM180-XUEYU010`, 
`edo fetch`,

now when I run checkout on another stage, for example  `edo checkout DEV-1-ESCM180-XUEYU01`,
I get error messages below:

> yx666766@8CWL0Z2 MINGW64 /c/experiments/edo/test2
$ edo checkout DEV-1-ESCM180-XUEYU01
Changes detected in working directory, commit removal of file: './ASMPGM/BAD'
Changes detected in working directory, commit removal of file: './COBCOPY/CPY'
Changes detected in working directory, commit removal of file: './ASMPGM/C1BM4201'
Changes detected in working directory, commit removal of file: './ASMPGM/C1GA0020'
Changes detected in working directory, commit removal of file: './ASMPGM/C1GL0000'
Changes detected in working directory, commit removal of file: './ISPM/RENM'
Changes detected in working directory, commit removal of file: './ISPM/TESTADD2'
Error while running checkout!
Error: You have to save or discard your changes before checkout other stage.
    at Function.<anonymous> (C:\experiments\edo\endevor-cli\lib\api\EdoCheckoutApi.js:97:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\experiments\edo\endevor-cli\lib\api\EdoCheckoutApi.js:6:65)

These error messages are really strange to me. I'm not really sure what I'm supposed to do by reading these messages.

I'm on refactor branch.

**Comment by dankox** [comment]
Fixed in commit 48d26c99a26fa69a22a2e5d0a25f2fd58b18ddb8
